public static PrinterModel.DataBean x6_n = new PrinterModel.DataBean();
public DataBean() {
	this.grayPrint = false;
	this.grayThinEneragy = 0;
	this.grayModerationEneragy = 0;
	this.grayDeepenEneragy = 0;
	this.slowInterval = 0;
	this.grayImageSpeed = 40;
	this.grayScale = 1.0d;
	this.showElectricityModel = 0;
	this.addMorPix = true;
	this.A4XII = false;
	this.tattooPaper = false;
	this.tattooSpeed = 0;
	this.tattooEnergy = 0;
	this.addMorePixNum = -1;
	this.d1key = "";
	this.useNewActivation = false;
	this.lzoVersion = "";
	this.labelDevice = false;
	this.labelDeviceSize = 0.0f;
	this.autoLabelCheck = false;
	this.corePrint = false;
	this.modelNo = "X6"; //FROM FUNCTION
	this.model = 0; //FROM FUNCTION
	this.size = 2; //FROM FUNCTION
	this.paperSize = 384; //FROM FUNCTION
	this.printSize = 384; //FROM FUNCTION
	this.oneLength = 8; //FROM FUNCTION
	this.headName = "X6-"; //FROM FUNCTION
	this.canChangeMTU = true; //FROM FUNCTION
	this.devdpi = 200; //FROM FUNCTION
	this.imgPrintSpeed = 30; //FROM FUNCTION
	this.textPrintSpeed = 10; //FROM FUNCTION
	this.imgMTU = 123; //FROM FUNCTION
	this.newCompress = true; //FROM FUNCTION
	this.paperNum = 2; //FROM FUNCTION
	this.interval = 6; //FROM FUNCTION
	this.thinEneragy = 7500; //FROM FUNCTION
	this.moderationEneragy = 7500; //FROM FUNCTION
	this.deepenEneragy = 7500; //FROM FUNCTION
	this.textEneragy = 0; //FROM FUNCTION
	this.hasId = true; //FROM FUNCTION
	this.useSPP = false; //FROM FUNCTION
	this.newFormat = false; //FROM FUNCTION
	this.canPrintLabel = true; //FROM FUNCTION
	this.labelValue = "1"; //FROM FUNCTION
	this.backPaperNum = 40; //FROM FUNCTION
	this.detectionValue = 1; //FROM FUNCTION
}
